### ISSUE TITLE
Make option to execute override without asking

### ISSUE THREAD

**Issue by lucassimaoo** [igorlima/generator-js-type#8]
I'm automating the script for my own use and I would like to have an option to ignore and override files that already exists like "js-type-gen -c schema.json -y".

Great tool, Thanks

**Comment by schweller** [comment]
This issue is being solved at https://github.com/igorlima/js-type-gen/issues/12

**Comment by igorlima** [comment]
Yeoman generator has already an option to auto overwrite files :smirk: : 
https://github.com/yeoman/generator/blob/8c895a5fe48054dcc473d71ad1227a249cde3497/lib/base.js#L115

This feature will be included in the CLI by https://github.com/igorlima/js-type-gen/pull/13

Hence closing this issue.
